// Generated by CoffeeScript 1.6.3
var chai, homeSteps;

chai = require('chai');

chai.should();

homeSteps = function() {
  var driver, webdriver;
  webdriver = require('selenium-webdriver');
  driver = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).build();
  this.Given(/^I open ste.chn.agilent.com web page$/, function(callback) {
    driver.get('http://ste.chn.agilent.com');
    return callback();
  });
  return this.Then(/^I should see page title is: "(.*)"$/, function(title, callback) {
    return driver.getTitle().then(function(actual) {
      if (actual.should.equal(title)) {
        return callback();
      } else {
        return callback.fail(new Error('Expected to be on page with title: ' + title));
      }
    });
  });
};

module.exports = homeSteps;
