// Generated by CoffeeScript 1.6.3
(function() {
  var hooks;

  hooks = function() {
    return this.AfterFeatures(function(callback) {
      return airWorld.browser.quit();
    });
  };

  module.exports = hooks;

}).call(this);

/*
//@ sourceMappingURL=after_hook.map
*/
