// Generated by CoffeeScript 1.6.3
(function() {
  var airWorld, assert, chai, client, expect, webdriver;

  chai = require('chai');

  expect = chai.expect;

  assert = chai.assert;

  chai.should();

  webdriver = require('selenium-webdriver');

  client = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).build();

  airWorld = {
    localAiRServerUrl: 'http://localhost:1337',
    browser: client,
    visit: function() {
      return client.get(this.localAiRServerUrl);
    },
    getTitle: function() {
      return client.getTitle();
    },
    reset: function() {
      return console.log('reset AiR server DB');
    },
    prepareSampleTestCards: function() {
      return console.log('prepare 4 sample test cards for AiR');
    },
    inputSearchModel: function(model) {
      return client.findElement(webdriver.By.name('searchModelInput')).sendKeys(model);
    },
    clickButton: function(buttonName) {
      return client.findElement(webdriver.By.name('searchButton')).click();
    },
    getSearchResult: function() {
      return client.fineElement(webdriver.By.name('searchResultSummary')).getProperty('value');
    },
    quit: function() {
      return client.quit();
    }
  };

  module.exports = airWorld;

}).call(this);

/*
//@ sourceMappingURL=airWorld.map
*/
