// Generated by CoffeeScript 1.6.3
(function() {
  var airWorld, assert, chai, client, expect, webdriver;

  chai = require('chai');

  expect = chai.expect;

  assert = chai.assert;

  chai.should();

  webdriver = require('selenium-webdriver');

  client = new webdriver.Builder().withCapabilities(webdriver.Capabilities.chrome()).build();

  airWorld = {
    localAiRServerUrl: 'http://localhost:1337',
    browser: client,
    visit: function() {
      return client.get(this.localAiRServerUrl);
    },
    getTitle: function() {
      return client.getTitle();
    },
    reset: function() {
      return console.log('reset AiR server DB');
    },
    prepareSampleTestCards: function() {
      return console.log('prepare 4 sample test cards for AiR');
    },
    inputSearchModel: function(model) {
      return console.log('input given model number: ' + model + ' input model search textbox');
    },
    clickButton: function(buttonName) {
      return console.log("click button (" + buttonName + ") on AiR");
    },
    getSearchResult: function() {
      return console.log('return search result');
    }
  };

  module.exports = airWorld;

}).call(this);

/*
//@ sourceMappingURL=airWorld.map
*/
