// Generated by CoffeeScript 1.6.3
(function() {
  var airWorld, title;

  airWorld = require('./airWorld');

  airWorld.visit('http://www.google.com', function() {
    return console.log('finish visiting google.com');
  });

  title = airWorld.getTitle();

  console.log('retrieved title is: ' + title);

}).call(this);

/*
//@ sourceMappingURL=testAirWorld.map
*/
