// Generated by CoffeeScript 1.6.3
(function() {
  var search_test_card_steps;

  search_test_card_steps = function() {
    var hooks, pageObject;
    pageObject = require('../../support/airWorld');
    hooks = require('../../support/after_hook');
    this.Given(/^AiR server have 4 34970A test cards$/, function(next) {
      console.log('I need to prepare 4 test cards.');
      return next();
    });
    this.Given(/^I input "(.*)" into "Search Model Number" textbox$/, function(model, next) {
      return next();
    });
    this.When(/^I click "(.*)" button$/, function(buttonName, next) {
      return next();
    });
    this.Then(/^I should see (\d) test cards summary listed$/, function(count, next) {
      return next();
    });
    return this.Then(/^(\d) test cards properties are as expected$/, function(number, next) {
      return next();
    });
  };

  module.exports = search_test_card_steps;

}).call(this);

/*
//@ sourceMappingURL=search_test_card_steps.map
*/
